/// Flutter icons Bible
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bible
///      fonts:
///       - asset: fonts/Bible.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class Bible {
  Bible._();

  static const _kFontFam = 'Bible';

  static const IconData heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart_2 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart_3 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData heart_4 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData heart_filled = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData heart_5 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData heart_empty_1 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData heart_broken = const IconData(0xf028, fontFamily: _kFontFam);
}
